# This is a basic workflow to help you get started with Actions

name: CI and Netlify

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      # - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
  # publish:
  #   needs: [build]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@master

  #     - name: Publish
  #       uses: netlify/actions/build@master
  #       env:
  #         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  #         NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  # deploy:
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Checkout repo
  #     - uses: actions/checkout@v2
  #     - name: Install Dependencies
  #       run: npm install
  #     - name: Build site
  #       run: npm run build
  #     # Deploy the site with netlify-cli
  #     - name: Deploy Site
  #       env:
  #         NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  #         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  #       run: npx netlify-cli deploy --dir=public --prod
  deploy-to-production:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          REACT_APP_CLIENT_SECRET: ${{ secrets.REACT_APP_CLIENT_SECRET }}
          REACT_APP_PASSWORD: ${{ secrets.REACT_APP_PASSWORD }}
          REACT_APP_USER_AGENT: ${{ secrets.REACT_APP_USER_AGENT }}
          REACT_APP_USER_NAME: ${{ secrets.REACT_APP_USER_NAME }}:  
      - name: Deploy
        uses: nwtgck/actions-netlify@v1.1
        with:
#           deploy-message: ${{ github.event.head_commit.message }}
#           enable-commit-comment: false
#           github-token: ${{ secrets.GITHUB_TOKEN }}
          production-branch: master
          production-deploy: true
          publish-dir: "build"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
